#!/usr/bin/env bash

# A rebuild script that commits on a successful build. Taken from 0atman gist.

set -e

rebuild_type=0
conf_path=~/nixfiles/
while getopts 'sh' OPTION; do
    case "$OPTION" in
	s)
	    echo "debug: option s"
	    rebuild_type=0
	    conf_path=${conf_path}configuration.nix
	    ;;
	h)
	    echo "debug: option h"
	    rebuild_type=1
	    conf_path=${conf_path}home.nix
	    ;;
	?)
	    echo "supported flags: [-s] [-h] [-f]"
	    exit 1
	    ;;
    esac
shift
done

$EDITOR $conf_path

pushd ~/nixfiles/ > /dev/null

if git diff --quiet '*.nix'; then
    echo "No changed detected, exiting."
    popd > /dev/null
    exit 0
fi

alejandra . &>/dev/null \
    || (alejandra . ; echo "Formatting failed!" && exit 1)

git diff -U0 '*.nix'

echo "NixOS rebuilding..."

case "$rebuild_type" in
    0)
	sudo nixos-rebuild switch --flake . &>rebuild.log || (cat rebuild.log | grep --color error && exit 1)
	;;
    1)
	home-manager switch --flake . &>rebuild.log || (cat rebuild.log | grep --color error && exit 1)
	;;
    *)
	echo "Invalid rebuild type."
	exit 1
	;;
esac

echo "Build successful!"

current=$(nixos-rebuild list-generations | grep current)

git commit -am "$current"

popd > /dev/null
